export const STATIC_CARDS = [
  {
    id: 1,
    title: "Labourer Card (Green)",
    slug: "cscs-green-card",
    cardColor: "green",
    description:
      "For general construction labouring roles without trade qualifications. Requires Level 1 Health & Safety qualification and CITB Operative test. Entry-level card for site access while gaining experience.",
    amount: 49.99,
    isQualificationsNeed: true,
    qualificationName: "Level 1 Health & Safety + CITB Operative Test",
    extra: "Valid: 2 years (5-year renewal)",
    cardImage: "/images/cscs-cards/1.webp",
  },
  {
    id: 2,
    title: "Trainee Card (Red)",
    slug: "trainee",
    cardColor: "red",
    description:
      "For individuals registered on construction qualifications like NVQs or degrees. Allows site work while completing training and progressing to skilled cards.",
    amount: 39.99,
    isQualificationsNeed: true,
    qualificationName: "NVQ / Degree / Training + CITB Operative Test",
    extra: "Valid: 2–5 years",
    cardImage: "/images/cscs-cards/25.webp",
  },
  {
    id: 3,
    title: "Apprentice Card (Red)",
    slug: "red-apprentice",
    cardColor: "red",
    description:
      "Free card for workers on recognised apprenticeships. Provides full site access during training. Must progress after completion.",
    amount: 0,
    isQualificationsNeed: true,
    qualificationName: "Apprenticeship Registration + CITB Test",
    extra: "Valid: 4 years 6 months",
    cardImage: "/images/cscs-cards/13.webp",
  },
  {
    id: 4,
    title: "Experienced Worker Card (Red)",
    slug: "red-experienced-worker",
    cardColor: "red",
    description:
      "Temporary card for workers with 1+ year experience enrolled in NVQ. Helps transition to skilled qualification while working.",
    amount: 34.99,
    isQualificationsNeed: true,
    qualificationName: "1+ Year Experience + NVQ Enrolment",
    extra: "Valid: 1 year (non-renewable)",
    cardImage: "/images/cscs-cards/9.webp",
  },
  {
    id: 5,
    title: "Experienced Technical, Supervisor or Manager Card (Red)",
    slug: "red-technical",
    cardColor: "red",
    description:
      "For supervisors, managers, and technical workers with experience working towards qualifications. Temporary access during progression.",
    amount: 44.99,
    isQualificationsNeed: true,
    qualificationName: "Supervisory Experience + Relevant Qualification",
    extra: "Valid: Temporary | Test: Role-based",
    cardImage: "/images/cscs-cards/7.webp",
  },
  {
    id: 6,
    title: "Blue Skilled Worker Card",
    slug: "blue-skilled-worker",
    cardColor: "blue",
    description:
      "For qualified tradespeople with NVQ Level 2 or completed apprenticeship. Standard card for skilled construction workers.",
    amount: 59.99,
    isQualificationsNeed: true,
    qualificationName: "NVQ Level 2 / Apprenticeship",
    extra: "Valid: 5 years",
    cardImage: "/images/cscs-cards/2.webp",
  },
  {
    id: 7,
    title: "Gold Skilled Worker Card (Advanced Craft)",
    slug: "gold-skilled-worker",
    cardColor: "gold",
    description:
      "For advanced tradespeople with NVQ Level 3. Recognises higher skill level and ability to handle complex work.",
    amount: 69.99,
    isQualificationsNeed: true,
    qualificationName: "NVQ Level 3",
    extra: "Valid: 5 years",
    cardImage: "/images/cscs-cards/3.webp",
  },
  {
    id: 8,
    title: "Gold Supervisory Card",
    slug: "gold-supervisor",
    cardColor: "gold",
    description:
      "For supervisors with NVQ Level 3 or 4. Demonstrates ability to manage teams, safety, and site operations.",
    amount: 74.99,
    isQualificationsNeed: true,
    qualificationName: "NVQ Level 3–4 (Supervisory)",
    extra: "Valid: 5 years | Test: CITB Supervisor",
    cardImage: "/images/cscs-cards/10.webp",
  },
  {
    id: 9,
    title: "Black Manager Card",
    slug: "black-manager",
    cardColor: "black",
    description:
      "For senior managers with NVQ Level 4–7. Highest vocational card for construction management professionals.",
    amount: 79.99,
    isQualificationsNeed: true,
    qualificationName: "NVQ Level 4–7",
    extra: "Valid: 5 years | Test: CITB MAP",
    cardImage: "/images/cscs-cards/12.webp",
  },
  {
    id: 10,
    title: "Academically Qualified Person Card (White - AQP)",
    slug: "white-academically",
    cardColor: "white",
    description:
      "For professionals with construction-related degrees or diplomas. Ideal for surveyors, engineers, and technical roles.",
    amount: 69.99,
    isQualificationsNeed: true,
    qualificationName: "Degree / HND / NEBOSH",
    extra: "Valid: 5 years",
    cardImage: "/images/cscs-cards/14.webp",
  },
  {
    id: 11,
    title: "Professionally Qualified Person Card (White - PQP)",
    slug: "white-professionally",
    cardColor: "white",
    description:
      "For members of professional bodies like CIOB, RICS, ICE. Confirms professional competence and status.",
    amount: 84.99,
    isQualificationsNeed: true,
    qualificationName: "CIOB / RICS / ICE Membership",
    extra: "Valid: 5 years",
    cardImage: "/images/cscs-cards/6.webp",
  },
  {
    id: 12,
    title: "Provisional Card (Red)",
    slug: "red-provisional",
    cardColor: "red",
    description:
      "Short-term card for workers in probation period. Allows temporary site access before moving to proper qualification route.",
    amount: 29.99,
    isQualificationsNeed: false,
    qualificationName: null,
    extra: "Valid: 6 months (non-renewable)",
    cardImage: "/images/cscs-cards/11.webp",
  },
  {
    id: 13,
    title: "Industry Placement Card (Red)",
    slug: "industry-placement",
    cardColor: "red",
    description:
      "For students on construction courses requiring site placement. Supports practical experience during studies.",
    amount: 39.99,
    isQualificationsNeed: true,
    qualificationName: "Course Registration (T-Level/Vocational)",
    extra: "Valid: 3 years (non-renewable)",
    cardImage: "/images/cscs-cards/8.webp",
  },
];